CXXFLAGS := -std=c++1y -Wall -Wextra -g


# cpp files that contains a "main" function
MAIN := $(shell find -name "*.cpp" -exec grep -l "^int main" {} +)

# cpp files without "main" function
NOMAIN := $(shell find -name "*.cpp" -exec grep -L "^int main" {} +)

# All cpp files
SOURCES := $(MAIN) $(NOMAIN)

# Files with dependency information
DEP := $(SOURCES:.cpp=.dep.mk)

# Object files
OBJ := $(SOURCES:.cpp=.o)

# Programs generated by this project
PROGRAMS := $(MAIN:.cpp=)


$(foreach program,$(PROGRAMS),$(eval OBJ-$(program) = $(OBJ)))
include $(wildcard $(DEP))

# Makefile targets

.DEFAULT_GOAL := all

.PHONY: all
all: $(PROGRAMS)

$(PROGRAMS): %: %.o $(NOMAIN:.cpp=.o)
	$(CXX) $(CXXFLAGS) $^ -o $*

$(OBJ): %.o : %.cpp %.dep.mk
	$(CXX) $(CXXFLAGS) -c $< -o $@ -MMD -MF $*.dep.mk -MP

# This rule exists so that the previous rule is always run,
# whenever it does not exist.
$(DEP): %.dep.mk:

.PHONY: mostlyclean clean
mostlyclean:
	-find \( -name "*.o" -or -name "*.dep.mk" \) -exec rm '{}' \;

clean: mostlyclean
	-rm -f $(PROGRAMS)
